<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admins
        DB::table('admins')->insert([
            [
                'name'=>'Bernard',
                'email'=>'bernard@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Feylin',
                'email'=>'feylin@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Matthew',
                'email'=>'matthew@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Michelle',
                'email'=>'michelle@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
        ]);

        // logs
        DB::table('logs')->insert([
            [
                'admin_id' => 1,
                'action' => 'login',
                'target_table' => 'admins',
                'description' => 'Admin ADM01 logged in',
                'created_at' => now(),
            ],
            [
                'admin_id' => 3,
                'action' => 'delete',
                'target_table' => 'products',
                'description' => 'Admin ADM01 deleted product PRD11',
                'created_at' => now(),
            ],
            [
                'admin_id' => 2,
                'action' => 'update',
                'target_table' => 'orders',
                'description' => 'Admin ADM02 updated order status for ORD045 to shipped',
                'created_at' => now(),
            ],
            [
                'admin_id' => 4,
                'action' => 'create',
                'target_table' => 'categories',
                'description' => 'Admin ADM01 added new category "Running Shoes"',
                'created_at' => now(),
            ],
            [
                'admin_id' => 3,
                'action' => 'review',
                'target_table' => 'product_reviews',
                'description' => 'User USR03 submitted review for product PRD05',
                'created_at' => now(),
            ],
            [
                'admin_id' => 4,
                'action' => 'add_to_cart',
                'target_table' => 'carts',
                'description' => 'User USR04 added product PRD07 to cart',
                'created_at' => now(),
            ],
            [
                'admin_id' => 2,
                'action' => 'register',
                'target_table' => 'users',
                'description' => 'User USR06 registered an account',
                'created_at' => now(),
            ],
            [
                'admin_id' => 2,
                'action' => 'forgot_password',
                'target_table' => 'password_resets',
                'description' => 'User USR02 requested password reset',
                'created_at' => now(),
            ],
            [
                'admin_id' => 1,
                'action' => 'wishlist_add',
                'target_table' => 'wishlists',
                'description' => 'User USR05 added product PRD09 to wishlist',
                'created_at' => now(),
            ],
            [
                'admin_id' => 3,
                'action' => 'api_login',
                'target_table' => 'api_tokens',
                'description' => 'User USR01 authenticated via mobile API',
                'created_at' => now(),
            ],
        ]);

        // Customers
        DB::table('customers')->insert([
            [
                'name' => 'Rian Pratama',
                'email' => 'rian@example.com',
                'password' => Hash::make('rianpass'),
                'address' => 'Jl. Merdeka No. 1',
                'phone_number' => '081234567890',
                'registration_date' => now()->subDays(3),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayu Lestari',
                'email' => 'ayu@example.com',
                'password' => Hash::make('ayupass'),
                'address' => 'Jl. Kenanga No. 5',
                'phone_number' => '081234567891',
                'registration_date' => now()->subDays(5),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'password' => Hash::make('budipass'),
                'address' => 'Jl. Anggrek No. 10',
                'phone_number' => '081222334455',
                'registration_date' => now()->subDays(6),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Citra Dewi',
                'email' => 'citra.dewi@example.com',
                'password' => Hash::make('citrapass'),
                'address' => 'Jl. Melati No. 3',
                'phone_number' => '081334455667',
                'registration_date' => now()->subDays(2),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dedi Gunawan',
                'email' => 'dedi.gunawan@example.com',
                'password' => Hash::make('dedipass'),
                'address' => 'Jl. Kemuning No. 18',
                'phone_number' => '081556677889',
                'registration_date' => now()->subDays(4),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eka Putri',
                'email' => 'eka.putri@example.com',
                'password' => Hash::make('ekapass'),
                'address' => 'Jl. Mawar No. 21',
                'phone_number' => '081766889900',
                'registration_date' => now()->subDays(1),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fajar Rahman',
                'email' => 'fajar.rahman@example.com',
                'password' => Hash::make('fajarpass'),
                'address' => 'Jl. Dahlia No. 6',
                'phone_number' => '081909876543',
                'registration_date' => now()->subDays(7),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gina Anindya',
                'email' => 'gina.anindya@example.com',
                'password' => Hash::make('ginapass'),
                'address' => 'Jl. Teratai No. 15',
                'phone_number' => '081888999000',
                'registration_date' => now()->subDays(8),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hadi Kusuma',
                'email' => 'hadi.kusuma@example.com',
                'password' => Hash::make('hadipass'),
                'address' => 'Jl. Sakura No. 8',
                'phone_number' => '081712345678',
                'registration_date' => now()->subDays(9),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intan Sari',
                'email' => 'intan.sari@example.com',
                'password' => Hash::make('intanpass'),
                'address' => 'Jl. Cendana No. 12',
                'phone_number' => '081623456789',
                'registration_date' => now()->subDays(10),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);


        // Categories
        DB::table('categories')->insert([
            [
                'category_name' => 'Running',
                'description' => 'Sepatu untuk lari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Casual',
                'description' => 'Sepatu santai sehari-hari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Basketball',
                'description' => 'Sepatu untuk bermain basket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Training',
                'description' => 'Sepatu untuk latihan atau gym',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Hiking',
                'description' => 'Sepatu mendaki gunung dan outdoor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Soccer',
                'description' => 'Sepatu khusus sepak bola',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Skateboarding',
                'description' => 'Sepatu untuk olahraga skateboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Slip-On',
                'description' => 'Sepatu tanpa tali yang mudah dipakai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Formal',
                'description' => 'Sepatu resmi untuk ke kantor atau acara formal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Sandals',
                'description' => 'Sandal santai dan nyaman untuk sehari-hari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


        // Products
        DB::table('products')->insert([
            [
                'name' => 'Nike Zoom Fly',
                'description' => 'Sepatu lari super cepat',
                'price' => 1750000,
                'stock' => 20,
                'size' => '42',
                'image_url' => null,
                'category_id' => '1',
                'date_added' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Air Force 1',
                'description' => 'Sepatu casual ikonik',
                'price' => 1500000,
                'stock' => 15,
                'size' => '41',
                'image_url' => null,
                'category_id' => '2',
                'date_added' => now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Air Zoom Pegasus',
                'description' => 'Sepatu lari dengan kenyamanan maksimal',
                'price' => 1600000,
                'stock' => 18,
                'size' => '43',
                'image_url' => null,
                'category_id' => '1',
                'date_added' => now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Air Max 90',
                'description' => 'Sepatu casual dengan desain retro',
                'price' => 1450000,
                'stock' => 12,
                'size' => '40',
                'image_url' => null,
                'category_id' => '2',
                'date_added' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike LeBron 18',
                'description' => 'Sepatu basket dengan teknologi terbaru',
                'price' => 2500000,
                'stock' => 10,
                'size' => '44',
                'image_url' => null,
                'category_id' => '3',
                'date_added' => now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Zoom Freak 2',
                'description' => 'Sepatu basket ringan dan responsif',
                'price' => 2300000,
                'stock' => 8,
                'size' => '45',
                'image_url' => null,
                'category_id' => '3', 
                'date_added' => now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Free TR8',
                'description' => 'Sepatu latihan dengan fleksibilitas tinggi',
                'price' => 1400000,
                'stock' => 22,
                'size' => '42',
                'image_url' => null,
                'category_id' => '4', 
                'date_added' => now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike React Infinity Run',
                'description' => 'Sepatu lari dengan bantalan empuk',
                'price' => 2000000,
                'stock' => 14,
                'size' => '43',
                'image_url' => null,
                'category_id' => '1',
                'date_added' => now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike Air Zoom Structure 23',
                'description' => 'Sepatu lari dengan stabilitas ekstra',
                'price' => 1800000,
                'stock' => 17,
                'size' => '44',
                'image_url' => null,
                'category_id' => '1', 
                'date_added' => now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nike SB Dunk Low',
                'description' => 'Sepatu skateboarding dengan desain streetwear',
                'price' => 1600000,
                'stock' => 11,
                'size' => '42',
                'image_url' => null,
                'category_id' => '7', 
                'date_added' => now()->subDays(11),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Cart Items
        DB::table('cart_items')->insert([
            [
                'customer_id' => '1',
                'product_id' => '1', 
                'quantity' => 2,
                'added_at' => now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '2', 
                'product_id' => '2',
                'quantity' => 1,
                'added_at' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '3',
                'product_id' => '3', 
                'quantity' => 3,
                'added_at' => now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '4', 
                'product_id' => '4',
                'quantity' => 1,
                'added_at' => now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '5', 
                'product_id' => '5',
                'quantity' => 2,
                'added_at' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '6',
                'product_id' => '6', 
                'quantity' => 1,
                'added_at' => now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '7', 
                'product_id' => '7', 
                'quantity' => 1,
                'added_at' => now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '8',
                'product_id' => '8',
                'quantity' => 2,
                'added_at' => now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '9',
                'product_id' => '9', 
                'quantity' => 1,
                'added_at' => now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '10', 
                'product_id' => '10',
                'quantity' => 1,
                'added_at' => now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Product Reviews
        DB::table('product_reviews')->insert([
            [
                'customer_id' => '1',
                'product_id' => '1',
                'rating' => 5,
                'comment' => 'Sepatu lari yang sangat nyaman dan cepat!',
                'review_date' => now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '2', 
                'product_id' => '2',
                'rating' => 4,
                'comment' => 'Desainnya keren, tapi sedikit kaku di bagian pergelangan.',
                'review_date' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '3', 
                'product_id' => '3', 
                'rating' => 5,
                'comment' => 'Sepatu lari yang sempurna untuk jarak jauh.',
                'review_date' => now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '4', 
                'product_id' => '4',
                'rating' => 3,
                'comment' => 'Sepatu nyaman, tapi sedikit berat.',
                'review_date' => now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '5', 
                'product_id' => '5',
                'rating' => 5,
                'comment' => 'Sangat cocok untuk bermain basket, sangat responsif.',
                'review_date' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '6', 
                'product_id' => '6', 
                'rating' => 4,
                'comment' => 'Sepatu basket yang sangat bagus, tapi harga sedikit tinggi.',
                'review_date' => now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '7',
                'product_id' => '7', 
                'rating' => 3,
                'comment' => 'Cukup nyaman, namun kualitas bahan bisa lebih baik.',
                'review_date' => now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '8',
                'product_id' => '8',
                'rating' => 5,
                'comment' => 'Sepatu yang sangat nyaman untuk jogging jarak jauh.',
                'review_date' => now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '9', 
                'product_id' => '9', 
                'rating' => 4,
                'comment' => 'Cocok untuk lari di jalan raya, tetapi agak keras di bawah.',
                'review_date' => now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => '10', 
                'product_id' => '10', 
                'rating' => 4,
                'comment' => 'Sepatu santai yang sangat stylish, tapi agak sempit di bagian depan.',
                'review_date' => now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Wishlists
        DB::table('wishlists')->insert([
            [
                'customer_id' => 1, 
                'product_id' => 2,  
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 7,  
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 1, 
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 4,  
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3, 
                'product_id' => 3, 
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4, 
                'product_id' => 5,  
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5, 
                'product_id' => 6, 
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6, 
                'product_id' => 8, 
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 7, 
                'product_id' => 10,
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 8, 
                'product_id' => 9,  
                'added_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // orders
        DB::table('orders')->insert([
            [
                'customer_id' => 1, 
                'order_date' => now()->subDays(2),
                'status' => 'Completed',
                'total_amount' => 1750000 * 2 + 1500000, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2, 
                'order_date' => now()->subDays(3),
                'status' => 'Processing',
                'total_amount' => 1600000 * 3 + 1450000 * 2, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3, 
                'order_date' => now()->subDays(4),
                'status' => 'Shipped',
                'total_amount' => 2500000 + 2300000, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4, 
                'order_date' => now()->subDays(5),
                'status' => 'Completed',
                'total_amount' => 1400000 * 2 + 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5, 
                'order_date' => now()->subDays(6),
                'status' => 'Pending',
                'total_amount' => 1800000 * 2 + 1600000, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // order details
        DB::table('order_details')->insert([
            [
                'order_id' => 1,
                'product_id' => 1,
                'quantity' => 2,
                'unit_price' => 1750000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 1,
                'product_id' => 2,
                'quantity' => 1,
                'unit_price' => 1500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 2,
                'product_id' => 3, 
                'quantity' => 3,
                'unit_price' => 1600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 2,
                'product_id' => 4,
                'quantity' => 2,
                'unit_price' => 1450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 3,
                'product_id' => 5, 
                'quantity' => 1,
                'unit_price' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 3,
                'product_id' => 6,
                'quantity' => 1,
                'unit_price' => 2300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 4,
                'product_id' => 7,
                'quantity' => 2,
                'unit_price' => 1400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 4,
                'product_id' => 8, 
                'quantity' => 1,
                'unit_price' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 5,
                'product_id' => 9, 
                'quantity' => 2,
                'unit_price' => 1800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 5,
                'product_id' => 10,
                'quantity' => 1,
                'unit_price' => 1600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Payments
        DB::table('payments')->insert([
            [
                'order_id' => 1, 
                'payment_method' => 'Credit Card',
                'payment_status' => 'Completed',
                'payment_date' => now()->subDays(2),
                'total_paid' => 1750000 * 2 + 1500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 2, 
                'payment_method' => 'PayPal',
                'payment_status' => 'Completed',
                'payment_date' => now()->subDays(3),
                'total_paid' => 1600000 * 3 + 1450000 * 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 3, 
                'payment_method' => 'Bank Transfer',
                'payment_status' => 'Completed',
                'payment_date' => now()->subDays(4),
                'total_paid' => 2500000 + 2300000, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 4, 
                'payment_method' => 'Credit Card',
                'payment_status' => 'Completed',
                'payment_date' => now()->subDays(5),
                'total_paid' => 1400000 * 2 + 2000000, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 5, 
                'payment_method' => 'Cash on Delivery',
                'payment_status' => 'Pending',
                'payment_date' => now()->subDays(6),
                'total_paid' => 1800000 * 2 + 1600000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Shipping
        DB::table('shipping')->insert([
            [
                'order_id' => 1,
                'shipping_address' => 'Jl. Merdeka No. 10, Jakarta',
                'courier' => 'JNE',
                'tracking_number' => 'JNE123456789',
                'shipping_status' => 'Shipped',
                'shipped_date' => now()->subDays(1),
                'delivered_date' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 2,
                'shipping_address' => 'Jl. Raya No. 50, Surabaya',
                'courier' => 'TIKI',
                'tracking_number' => 'TIKI987654321',
                'shipping_status' => 'Processing',
                'shipped_date' => null,
                'delivered_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 3,
                'shipping_address' => 'Jl. Sejahtera No. 5, Bandung',
                'courier' => 'POS Indonesia',
                'tracking_number' => 'POS123987654',
                'shipping_status' => 'Shipped',
                'shipped_date' => now()->subDays(2),
                'delivered_date' => now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 4,
                'shipping_address' => 'Jl. Merpati No. 8, Yogyakarta',
                'courier' => 'Gojek',
                'tracking_number' => 'GOJEK456123789',
                'shipping_status' => 'Delivered',
                'shipped_date' => now()->subDays(3),
                'delivered_date' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 5,
                'shipping_address' => 'Jl. Senayan No. 22, Jakarta',
                'courier' => 'J&T Express',
                'tracking_number' => 'JTEX987123456',
                'shipping_status' => 'Pending',
                'shipped_date' => null, 
                'delivered_date' => null, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}