<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admins
        DB::table('admins')->insert([
            [
                'name'=>'Bernard',
                'email'=>'bernard@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Feylin',
                'email'=>'feylin@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Matthew',
                'email'=>'matthew@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
                'name'=>'Michelle',
                'email'=>'michelle@gmail.com',
                'password'=>'1234',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
        ]);

        // Customers
        DB::table('customers')->insert([
            [
                'name' => 'Rian Pratama',
                'email' => 'rian@example.com',
                'password' => Hash::make('rianpass'),
                'address' => 'Jl. Merdeka No. 1',
                'phone_number' => '081234567890',
                'registration_date' => now()->subDays(3),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayu Lestari',
                'email' => 'ayu@example.com',
                'password' => Hash::make('ayupass'),
                'address' => 'Jl. Kenanga No. 5',
                'phone_number' => '081234567891',
                'registration_date' => now()->subDays(5),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'password' => Hash::make('budipass'),
                'address' => 'Jl. Anggrek No. 10',
                'phone_number' => '081222334455',
                'registration_date' => now()->subDays(6),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Citra Dewi',
                'email' => 'citra.dewi@example.com',
                'password' => Hash::make('citrapass'),
                'address' => 'Jl. Melati No. 3',
                'phone_number' => '081334455667',
                'registration_date' => now()->subDays(2),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dedi Gunawan',
                'email' => 'dedi.gunawan@example.com',
                'password' => Hash::make('dedipass'),
                'address' => 'Jl. Kemuning No. 18',
                'phone_number' => '081556677889',
                'registration_date' => now()->subDays(4),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eka Putri',
                'email' => 'eka.putri@example.com',
                'password' => Hash::make('ekapass'),
                'address' => 'Jl. Mawar No. 21',
                'phone_number' => '081766889900',
                'registration_date' => now()->subDays(1),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fajar Rahman',
                'email' => 'fajar.rahman@example.com',
                'password' => Hash::make('fajarpass'),
                'address' => 'Jl. Dahlia No. 6',
                'phone_number' => '081909876543',
                'registration_date' => now()->subDays(7),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gina Anindya',
                'email' => 'gina.anindya@example.com',
                'password' => Hash::make('ginapass'),
                'address' => 'Jl. Teratai No. 15',
                'phone_number' => '081888999000',
                'registration_date' => now()->subDays(8),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hadi Kusuma',
                'email' => 'hadi.kusuma@example.com',
                'password' => Hash::make('hadipass'),
                'address' => 'Jl. Sakura No. 8',
                'phone_number' => '081712345678',
                'registration_date' => now()->subDays(9),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intan Sari',
                'email' => 'intan.sari@example.com',
                'password' => Hash::make('intanpass'),
                'address' => 'Jl. Cendana No. 12',
                'phone_number' => '081623456789',
                'registration_date' => now()->subDays(10),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);


        // Category
        DB::table('category')->insert([
            [
                'category_name' => 'Running',
                'description' => 'Sepatu untuk lari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Casual',
                'description' => 'Sepatu santai sehari-hari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Basketball',
                'description' => 'Sepatu untuk bermain basket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Training',
                'description' => 'Sepatu untuk latihan atau gym',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Soccer',
                'description' => 'Sepatu khusus sepak bola',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_name' => 'Sandals',
                'description' => 'Sandal santai dan nyaman untuk sehari-hari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


        // Product
        DB::table('product')->insert([
            [
                'name' => 'Dunk Low',
                'gender' => 'Women',
                'description' => 'The Nike Dunk Low is a classic, low-top sneaker known for its sleek silhouette, versatile style, and roots in basketball and street culture.',
                'price' => 1549000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cortez Textile',
                'gender' => 'Unisex',
                'description' => 'The Nike Cortez Textile is a lightweight, retro running shoe that features a breathable fabric upper, classic low-profile design, and timeless style rooted in 1970s sneaker culture.',
                'price' => 1399000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Air Jordan 1 Low',
                'gender' => 'Men',
                'description' => 'The Air Jordan 1 Low is a low-cut version of the iconic AJ1, offering a sleek, casual take on the classic basketball silhouette with premium materials and timeless Jordan style.',
                'price' => 1729000,
                'status' => 'active',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blazer Mid 77 Vintage',
                'gender' => 'Women',
                'description' => 'The Nike Blazer Mid 77 Vintage is a retro-inspired sneaker featuring a mid-top design, exposed foam tongue, and vintage detailing that nods to its basketball roots from the late 70s.',
                'price' => 1729000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giannis Immortality 4 EP',
                'gender' => 'Unisex',
                'description' => 'The Nike Giannis Immortality 4 EP is a lightweight, outdoor-ready basketball shoe designed for versatile players, featuring a padded, supportive heel, upgraded traction pattern, and internal containment system for enhanced control and mobility on the court.',
                'price' => 1199000,
                'status' => 'active',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zoom Vomero 5',
                'gender' => 'Men',
                'description' => 'The Nike Zoom Vomero 5 is a versatile sneaker that combines early-2000s running aesthetics with modern comfort, featuring breathable mesh, durable overlays, and responsive Zoom Air cushioning for all-day wear.',
                'price' => 2489000,
                'status' => 'active',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Air Max Plus',
                'gender' => 'Women',
                'description' => 'The Nike Air Max Plus is a bold, street-ready sneaker known for its wavy design and Tuned Air cushioning.',
                'price' => 2389000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LeBron XXI Prime 96 EP',
                'gender' => 'Men',
                'description' => 'The Nike LeBron XXI Prime 96 EP is a bold basketball shoe that blends LeBron’s signature design with Deion Sanders-inspired details like claw marks and a midfoot strap.',
                'price' => 3169000,
                'status' => 'active',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CITY',
                'gender' => 'Unisex',
                'description' => 'The CITY collection celebrates urban culture with a range of sneakers and apparel designed for style, performance, and connection to city life.',
                'price' => 4089000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vaporfly 4',
                'gender' => 'Men',
                'description' => 'The Nike Vaporfly 4 is a high-performance racing shoe featuring lightweight construction and advanced ZoomX foam for optimal speed and energy return.',
                'price' => 3989000,
                'status' => 'active',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dunk Low SE',
                'gender' => 'Women',
                'description' => 'The Nike Dunk Low SE is a stylish, low-top sneaker with unique colorways and premium materials, offering a versatile look for casual wear.',
                'price' => 1909000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Air Force 1 07',
                'gender' => 'Unisex',
                'description' => 'The Nike Air Force 1 07 is a timeless low-top sneaker that blends classic 80s basketball design with modern comfort.',
                'price' => 1190000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dunk High',
                'gender' => 'Men',
                'description' => 'The Nike Dunk High is a high-top sneaker that blends retro basketball heritage with modern streetwear appeal, featuring bold colorways and durable construction for everyday wear.',
                'price' => 1859000,
                'status' => 'active',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $data = [
            [1, 'dunklow_gray'],
            [2, 'dunklow_green'],
            [3, 'dunklow_blue'],
            [4, 'cortez_blue'],
            [5, 'cortez_pink'],
            [6, 'cortez_brown'],
            [7, 'cortez_green'],
            [8, 'jordan_red'],
            [9, 'jordan_turquoise'],
            [10, 'jordan_mocha'],
            [11, 'jordan_black'],
            [12, 'blazer_black'],
            [13, 'blazer_pink'],
            [14, 'blazer_maroon'],
            [15, 'blazer_blue'],
            [16, 'giannis_white'],
            [17, 'giannis_purple'],
            [18, 'giannis_blue'],
            [19, 'giannis_pink'],
            [20, 'vomero_pink'],
            [21, 'vomero_cream'],
            [22, 'vomero_green'],
            [23, 'vomero_blue'],
            [24, 'airmax_black'],
            [25, 'airmax_red'],
            [26, 'airmax_orange'],
            [27, 'airmax_green'],
            [28, 'lebron_red'],
            [29, 'lebron_black'],
            [30, 'city_green'],
            [31, 'city_pink'],
            [32, 'city_brown'],
            [33, 'city_blue'],
            [34, 'vaporfly_black'],
            [35, 'vaporfly_navy'],
            [36, 'vaporfly_cream'],
            [37, 'vaporfly_blue'],
            [38, 'retroSE_gray'],
            [39, 'retroSE_green'],
            [40, 'retroSE_brown'],
            [41, 'retroSE_navy'],
            [42, 'af_cream'],
            [43, 'af_turquoise'],
            [44, 'af_red'],
            [45, 'dunkhigh_navy'],
            [46, 'dunkhigh_gray'],
            [47, 'dunkhigh_blue'],
            [48, 'dunkhigh_red'],
        ];

        foreach ($data as [$colorId, $prefix]) {
            DB::table('product_color_image')->insert([
                'color_id'   => $colorId,
                'image_kiri'  => "{$prefix}_kiri.png",
                'image_kanan' => "{$prefix}_kanan.png",
                'image_atas'  => "{$prefix}_atas.png",
                'image_bawah' => "{$prefix}_bawah.png",
            ]);
        }


        // Product Reviews
        DB::table('product_reviews')->insert([
            [
                'customer_id' => 1,
                'product_id' => 1,
                'rating' => 5,
                'review_title' => 'Nyaman dan Ringan!',
                'comment' => 'Sepatu ini sangat nyaman dipakai untuk jogging pagi.',
                'review_date' => now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 1,
                'rating' => 4,
                'review_title' => 'Oke tapi agak sempit',
                'comment' => 'Enak dipakai tapi bagian depan terasa sempit.',
                'review_date' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 1,
                'rating' => 5,
                'review_title' => 'Perfect!',
                'comment' => 'Desain dan kenyamanannya luar biasa.',
                'review_date' => now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 2,
                'rating' => 3,
                'review_title' => 'Desain bagus tapi agak berat',
                'comment' => 'Bagus untuk gaya, tapi kurang cocok buat lari.',
                'review_date' => now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 2,
                'rating' => 4,
                'review_title' => 'Keren!',
                'comment' => 'Desainnya oke, cocok buat jalan santai.',
                'review_date' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 2,
                'rating' => 4,
                'review_title' => 'Mantap!',
                'comment' => 'Nyaman dipakai seharian.',
                'review_date' => now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 3,
                'rating' => 5,
                'review_title' => 'Luar biasa untuk marathon!',
                'comment' => 'Support yang baik dan empuk untuk lari jauh.',
                'review_date' => now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 3,
                'rating' => 5,
                'review_title' => 'Top banget!',
                'comment' => 'Salah satu sepatu terbaik yang saya punya.',
                'review_date' => now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 7,
                'product_id' => 3,
                'rating' => 4,
                'review_title' => 'Bagus, tapi warna cepat pudar',
                'comment' => 'Kenyamanan oke, tapi warna cepat memudar setelah dicuci.',
                'review_date' => now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 4,
                'rating' => 3,
                'review_title' => 'Sedikit berat',
                'comment' => 'Sepatu agak berat untuk lari cepat.',
                'review_date' => now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 4,
                'rating' => 4,
                'review_title' => 'Lumayan enak dipakai',
                'comment' => 'Sesuai harga, tidak mengecewakan.',
                'review_date' => now()->subDays(11),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 4,
                'rating' => 4,
                'review_title' => 'Cocok untuk harian',
                'comment' => 'Bagus untuk dipakai ke kampus atau kantor.',
                'review_date' => now()->subDays(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 5,
                'rating' => 5,
                'review_title' => 'Responsif dan nyaman',
                'comment' => 'Sepatu basket terbaik yang pernah saya coba.',
                'review_date' => now()->subDays(13),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 5,
                'rating' => 5,
                'review_title' => 'Powerful!',
                'comment' => 'Memberi performa tinggi saat di lapangan.',
                'review_date' => now()->subDays(14),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 7,
                'product_id' => 5,
                'rating' => 4,
                'review_title' => 'Bagus tapi agak mahal',
                'comment' => 'Kualitas bagus, tapi harga di atas rata-rata.',
                'review_date' => now()->subDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 6,
                'rating' => 4,
                'review_title' => 'Mantap buat olahraga indoor',
                'comment' => 'Cocok banget buat basket indoor.',
                'review_date' => now()->subDays(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 6,
                'rating' => 5,
                'review_title' => 'Enak dipakai dan keren!',
                'comment' => 'Desain dan performanya tidak mengecewakan.',
                'review_date' => now()->subDays(17),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 6,
                'rating' => 3,
                'review_title' => 'Agak kaku di awal',
                'comment' => 'Perlu beberapa kali pakai baru terasa nyaman.',
                'review_date' => now()->subDays(18),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 7,
                'rating' => 3,
                'review_title' => 'Kualitas bahan kurang',
                'comment' => 'Cukup nyaman tapi cepat aus.',
                'review_date' => now()->subDays(19),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 7,
                'rating' => 4,
                'review_title' => 'Enak buat dipakai harian',
                'comment' => 'Pas buat ke kampus, simple dan ringan.',
                'review_date' => now()->subDays(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 7,
                'rating' => 4,
                'review_title' => 'Desain oke, bahan biasa aja',
                'comment' => 'Tidak buruk, tapi tidak istimewa juga.',
                'review_date' => now()->subDays(21),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 8,
                'rating' => 5,
                'review_title' => 'Terbaik untuk jogging',
                'comment' => 'Nyaman dan tidak licin saat hujan.',
                'review_date' => now()->subDays(22),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 8,
                'rating' => 4,
                'review_title' => 'Nyaman tapi cepat kotor',
                'comment' => 'Harus sering dibersihkan kalau sering dipakai.',
                'review_date' => now()->subDays(23),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 8,
                'rating' => 4,
                'review_title' => 'Oke buat pemula',
                'comment' => 'Pas buat yang baru mulai lari rutin.',
                'review_date' => now()->subDays(24),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 7,
                'product_id' => 9,
                'rating' => 4,
                'review_title' => 'Cocok buat jalan raya',
                'comment' => 'Agak keras di awal, tapi lama-lama nyaman.',
                'review_date' => now()->subDays(25),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 9,
                'rating' => 3,
                'review_title' => 'Biasa aja',
                'comment' => 'Tidak terlalu istimewa, tapi cukup nyaman.',
                'review_date' => now()->subDays(26),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 9,
                'rating' => 5,
                'review_title' => 'Support yang bagus',
                'comment' => 'Bagus buat lari jarak menengah.',
                'review_date' => now()->subDays(27),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 10,
                'rating' => 4,
                'review_title' => 'Stylish dan ringan',
                'comment' => 'Bisa buat gaya dan nyaman juga.',
                'review_date' => now()->subDays(28),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 10,
                'rating' => 4,
                'review_title' => 'Depan agak sempit',
                'comment' => 'Cocok untuk kaki kecil, agak sempit untuk saya.',
                'review_date' => now()->subDays(29),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 10,
                'rating' => 5,
                'review_title' => 'Pilihan terbaik buat nongkrong',
                'comment' => 'Stylish dan nyaman, cocok buat ke mall.',
                'review_date' => now()->subDays(30),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}